/* AdForge — export the finished campaign as a tidy Markdown brief
   (brief + every scene's prompt, copy, score and image link). */
window.AF = window.AF || {};

AF.exporter = (function () {
  function buildMarkdown(state) {
    const b = state.brief || {};
    const lines = [];
    lines.push('# AdForge campaign — ' + (b.brandName || (state.input?.idea || 'Untitled')));
    lines.push('');
    lines.push('> ' + (state.input?.idea || ''));
    lines.push('');
    lines.push('## Creative brief');
    [['Angle', b.angle], ['Audience', b.audience], ['Key message', b.keyMessage],
     ['Tone', b.tone], ['Mood', b.mood], ['Visual style', b.visualStyle]]
      .forEach(([k, v]) => { if (v) lines.push('- **' + k + ':** ' + v); });
    if (Array.isArray(b.palette) && b.palette.length) lines.push('- **Palette:** ' + b.palette.join(', '));
    lines.push('');
    lines.push('## Master image prompt');
    lines.push('');
    lines.push('```');
    lines.push(state.masterPrompt || '');
    lines.push('```');
    lines.push('');
    lines.push('## Scenes');
    state.scenes.forEach((s, i) => {
      lines.push('');
      lines.push('### ' + (i + 1) + '. ' + (s.name || 'Scene') +
        (s.critique?.score != null ? '  _(score ' + s.critique.score + '/100)_' : ''));
      if (s.purpose) lines.push('_' + s.purpose + '_');
      if (s.copy) {
        lines.push('');
        if (s.copy.headline) lines.push('**' + s.copy.headline + '**  ');
        if (s.copy.subhead) lines.push(s.copy.subhead + '  ');
        if (s.copy.body) lines.push(s.copy.body);
        if (s.copy.cta) lines.push('');
        if (s.copy.cta) lines.push('**CTA:** ' + s.copy.cta);
        if (s.copy.caption) lines.push('**Caption:** ' + s.copy.caption);
      }
      lines.push('');
      lines.push('**Prompt:** ' + (s.prompt || ''));
      if (s.imageUrl) { lines.push(''); lines.push('Image: ' + s.imageUrl); }
      if (s.critique?.notes) lines.push('> Critic: ' + s.critique.notes);
    });
    lines.push('');
    lines.push('---');
    lines.push('_Generated by AdForge — multi-agent ad studio (' + AF.llm.activeBrain() + ')._');
    return lines.join('\n');
  }

  function downloadCampaign(state) {
    const md = buildMarkdown(state);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const name = (state.brief?.brandName || 'adforge-campaign').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    a.href = url; a.download = name + '.md';
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 3000);
  }

  return { buildMarkdown, downloadCampaign };
})();
